### ISSUE TITLE
add copyright/license and refs to readme

### ISSUE THREAD

**Issue by bvibber** [bvibber/yuv-buffer#7]

**Comment by MarkAshraf96** [comment]
That would be highly appreciated, and also preferably as a standalone file.

Including the license file, makes the packages compatible with license checkers and attribution file generators, that a lot of developers need for generating copyrights/attribution files.

I can easily create a PR with that change if you allow it.

**Comment by MarkAshraf96** [comment]
Thank you for doing this, can I ask you if you can also add the license as a separate file, so it can be compatible with license checkers?

**Comment by bvibber** [comment]
and done :D

**Comment by MarkAshraf96** [comment]
Last request, can you rename the file into "license" cause this is the standard usually. 
Thank you a lot for your efforts.

**Comment by bvibber** [comment]
heh sure :D

i'll bump another actual release a bit later, i have some other cleanup to do in here
